# .github/workflows/main.yml

name: Build & Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./tools/go.mod
          cache-dependency-path: |
            tools/go.sum
            go.sum
      - run: make test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Go Test Results
          path: .test/reports/**-test.xml
          reporter: java-junit
          fail-on-error: "true"
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Test Reports
          path: .test/reports/**

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./tools/go.mod
          check-latest: true
      - run: make lint
  
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./tools/go.mod
          check-latest: true
      - run: make build
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "Build artifacts"
          title: "Build artifacts"
          branch: "build-artifacts"
          base: main
          labels: build
          draft: false
      - if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

